services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn proxy_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: JeffersonFisherKey
        
